server:
  port: 8088
  tomcat:
    uri-encoding: utf-8
  servlet:
    context-path: /

datasource:
  local:
    url: jdbc:mysql://localhost:3306/jmis?useUnicode=true&useSSL=false&characterEncoding=utf8&rewriteBatchedStatements=true&autoReconnect=true
    jdbcUrl: jdbc:mysql://localhost:3306/jmis?useUnicode=true&useSSL=false&characterEncoding=utf8&rewriteBatchedStatements=true&autoReconnect=true
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    validationQuery: select 'x'
  remote:
    url: jdbc:mysql://localhost:3306/jmis_remote?useUnicode=true&useSSL=false&characterEncoding=utf8&rewriteBatchedStatements=true&autoReconnect=true
    jdbcUrl: jdbc:mysql://localhost:3306/jmis_remote?useUnicode=true&useSSL=false&characterEncoding=utf8&rewriteBatchedStatements=true&autoReconnect=true
    username: root
    password: root
    driverClassName: com.mysql.jdbc.Driver
    validationQuery: select 'x'